# https://travis-ci.org/conda/constructor

language: python
sudo: false

branches:
  only:
    - master

env:
  global:
    - CONSTRUCTOR_CACHE=/tmp/constructor_travis_ci

matrix:
  include:
    # Linux
    - os: linux
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 CONDA_CANARY=false CONDA_AUTO_UPDATE_CONDA=False
    - os: linux
      language: generic
      env: TRAVIS_PYTHON_VERSION=2.7 CONDA_CANARY=false CONDA_AUTO_UPDATE_CONDA=False
    - os: linux
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 CONDA_CANARY=true CONDA_AUTO_UPDATE_CONDA=False
    # OSX
    - os: osx
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 CONDA_CANARY=false CONDA_AUTO_UPDATE_CONDA=False
  allow_failures:
    - os: linux
      language: generic
      env: TRAVIS_PYTHON_VERSION=3.7 CONDA_CANARY=true CONDA_AUTO_UPDATE_CONDA=False

cache:
  directories:
    - $HOME/condacache/pkgs
    - $HOME/.cache/pip

install:
  # Install latest miniconda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      MINICONDA_OS=Linux ;
    else
      MINICONDA_OS=MacOSX ;
    fi ;
    MINICONDA_PYVERSION=${TRAVIS_PYTHON_VERSION:0:1} ;
    wget https://repo.anaconda.com/miniconda/Miniconda$MINICONDA_PYVERSION-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p "$HOME"/miniconda
  - source "$HOME"/miniconda/bin/activate
  - conda config --set always_yes yes
  - conda update conda -q --no-pin
  - conda config --add pkgs_dirs ~/condacache/pkgs
  # Install run dependencies
  - conda install pillow>=3.1 ruamel_yaml
  # Install test dependencies
  - conda install conda-forge::codecov pytest pytest-cov
  # Install this package
  - python setup.py develop
  - conda init
  # Install conda canary before running tests, ensure conda is updated
  - if [ "${CONDA_CANARY}" = "true" ]; then
      conda update conda -c conda-canary --no-pin;
    else
      conda update conda --no-pin;
    fi
  - source "$HOME"/miniconda/bin/activate
  - conda info
  - conda list

script:
  - pytest --cov=constructor constructor
  - python scripts/run_examples.py

after_success:
  - codecov
