name: constructor-dev
channels:
  - conda-forge
dependencies:
  - python
  - conda >=4.6
  - ruamel.yaml >=0.11.14,<0.19
  - conda-standalone # >=23.11.0
  - pillow >=3.1  # [osx or win]
  - jinja2
  - jsonschema >=4
  - pydantic ==2.11.*
