name: constructor-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - babel=2.11.0
  - beautifulsoup4=4.11.1
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.9.24
  - certifi=2022.9.24
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - colorama=0.4.6
  - cryptography=38.0.3
  - docutils=0.19
  - idna=3.4
  - imagesize=1.4.1
  - importlib-metadata=5.1.0
  - jinja2=3.1.2
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - linkify-it-py=2.0.0
  - markdown-it-py=2.1.0
  - markupsafe=2.1.1
  - mdit-py-plugins=0.3.1
  - mdurl=0.1.0
  - myst-parser=0.18.1
  - ncurses=6.3
  - openssl=3.0.7
  - packaging=21.3
  - pip=22.3.1
  - pycparser=2.21
  - pydata-sphinx-theme=0.12.0
  - pygments=2.13.0
  - pyopenssl=22.1.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.0
  - python_abi=3.11
  - pytz=2022.6
  - pyyaml=6.0
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=65.5.1
  - six=1.16.0
  - snowballstemmer=2.2.0
  - soupsieve=2.3.2.post1
  - sphinx=5.3.0
  - sphinx-copybutton=0.5.0
  - sphinx-design=0.3.0
  - sphinx-sitemap=2.2.1
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-mermaid=0.7.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.5
  - tk=8.6.12
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022f
  - uc-micro-py=1.0.1
  - urllib3=1.26.13
  - wheel=0.38.4
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.10.0
